export const config = {
	isr: {
		// Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
		// Setting the value to `false` means it will never expire.
		expiration: 10
	}
};

export function load() {
	const generatedAt = new Date().toISOString();
	return {
		generatedAt
	};
}
